name: Readme Test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  readme-test:
    name: Readme Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Test
        run: ./test/readme_test.sh
